// <auto-generated />
using System;
using Api.Infrastructures.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(PdfDbContext))]
    [Migration("20251202121408_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.PdfTemplates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("pdf_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Default contract template",
                            HtmlContent = "<!DOCTYPE html>\n<html>\n<head>\n    <meta charset='UTF-8'>\n    <style>\n        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }\n        .header { text-align: center; border-bottom: 3px solid #2c3e50; padding-bottom: 20px; margin-bottom: 40px; }\n        .header h1 { color: #2c3e50; font-size: 32px; text-transform: uppercase; margin: 0; }\n        .info { margin: 20px 0; padding: 15px; background: #f8f9fa; border-left: 4px solid #3498db; }\n        .info label { font-weight: bold; color: #2c3e50; }\n        .footer { margin-top: 50px; text-align: center; color: #7f8c8d; font-size: 12px; }\n    </style>\n</head>\n<body>\n    <div class='header'>\n        <h1>Service Contract</h1>\n        <p>Contract Number: {ContractNumber}</p>\n    </div>\n    <div class='info'>\n        <label>Client:</label> {FullName}<br>\n        <label>Email:</label> {Email}<br>\n        <label>Phone:</label> {Phone}<br>\n        <label>Period:</label> {StartDate} - {EndDate}<br>\n        <label>Amount:</label> {Currency} {TotalAmount}\n    </div>\n    <div class='footer'>\n        <p>Generated: {GeneratedDate}</p>\n    </div>\n</body>\n</html>",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "ContractTemplate"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
